hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - base

trainer:
  experiment_name: frozenlake-main


es_manager:
  train:
    env_configs:
      tags: ["FrozenLake"]
  val:
    env_configs:
      tags: ["FrozenLake"]
